stages:
  - build
  - container

build:
  image: golang:latest
  stage: build
  variables:
    REPO_NAME: git.plsnobully.me/emileet/cf-ddns-client
  before_script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/cf-ddns-client
  artifacts:
    paths:
      - cf-ddns-client

container:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cp ./data/example.json ./data/records.json
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
